PersonelMVCUI1/Models/Entity Framework/Kullanici.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI1.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public int PersonelId { get; set; }
        public string Sifre { get; set; }
        public string Role { get; set; }
    }
}

PersonelMVCUI1/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PersonelMVCUI1.Models.Entity_Framework;
using PersonelMVCUI1.ViewModels;

namespace PersonelMVCUI1.Controllers
{
    [Authorize(Roles = "A")]
    public class KullaniciController : Controller
    {

        PersonelDbEntities db = new PersonelDbEntities();


        public ActionResult Index()
        {
            var model = db.Kullanici.ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult Yeni()
        {
            var model = new KullaniciFormViewModel()
            {
                Personeller = db.Personel.ToList(),
                Kullanici = new Kullanici()
            };

            return View("KullaniciForm", model);
        }


        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Kullanici kullanici)
        {
            if (!ModelState.IsValid)
            {
                var model2 = new KullaniciFormViewModel()
                {
                    Personeller = db.Personel.ToList(),
                    Kullanici = kullanici
                };

                return View("KullaniciForm", model2);
            }

            MesajViewModel model = new MesajViewModel();
            if (kullanici.Id == 0)
            {
                model.Mesaj = kullanici.Email + " başarı ile eklendi.";
                db.Kullanici.Add(kullanici);
            }
            else
            {
                db.Entry(kullanici).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();

            model.Status = true;
            model.LinkText = "Kullanici Listesi";
            model.Url = "/Kullanici";

            return View("_Mesaj", model);
        }

        public ActionResult Guncelle(int id)
        {
            var model = new KullaniciFormViewModel()
            {
                Personeller = db.Personel.ToList(),
                Kullanici = db.Kullanici.Find(id)
            };

            return View("KullaniciForm", model);
        }

        public ActionResult Sil(int id)
        {
            var silinecekKullanici = db.Kullanici.Find(id);
            if (silinecekKullanici == null)
            { 
                return HttpNotFound(); 
            }
            db.Kullanici.Remove(silinecekKullanici);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KullaniciDetayi(int id)
        {
            var model = db.Kullanici.Where(x => x.Id == id);
            return PartialView(model);

            //Kullanici kullanici = db.Kullanici.Find(id);
            //if (kullanici == null) return HttpNotFound();

            //return View(kullanici);
        }


        //private PersonelDbEntities db = new PersonelDbEntities();

        //// GET: Kullanici
        //public ActionResult Index()
        //{
        //    return View(db.Kullanici.ToList());
        //}

        //// GET: Kullanici/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Kullanici kullanici = db.Kullanici.Find(id);
        //    if (kullanici == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(kullanici);
        //}

        //// GET: Kullanici/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Kullanici/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Ad,Sifre,Role")] Kullanici kullanici)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Kullanici.Add(kullanici);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(kullanici);
        //}

        //// GET: Kullanici/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Kullanici kullanici = db.Kullanici.Find(id);
        //    if (kullanici == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(kullanici);
        //}

        //// POST: Kullanici/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Ad,Sifre,Role")] Kullanici kullanici)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(kullanici).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(kullanici);
        //}

        //// GET: Kullanici/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Kullanici kullanici = db.Kullanici.Find(id);
        //    if (kullanici == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(kullanici);
        //}

        //// POST: Kullanici/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Kullanici kullanici = db.Kullanici.Find(id);
        //    db.Kullanici.Remove(kullanici);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

PersonelMVCUI1/Views/Kullanici/Index.cshtml
@model IEnumerable<PersonelMVCUI1.Models.Entity_Framework.Kullanici>
<br />
<br />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Kullanıcı Ekle", "Yeni", null, new { @class = "btn btn-success" })

<h2>Kullanici Listesi</h2>

<table class="table table-bordered table-striped" id="tblKullanicilar">
    <thead>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Güncelle</th>
            <th>Sil</th>
            <th>Kullanıcı Detayı</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var kullanici in Model)
        {
            <tr>
                <td>@kullanici.Id</td>
                <td>@kullanici.Email</td>   
                <td>@Html.ActionLink("Güncelle", "Guncelle", new { id = kullanici.Id }, new { @class = "btn btn-primary" })</td>         
                <td>@Html.ActionLink("Sil", "Sil", new { id = kullanici.Id }, new { @class = "btn btn-danger btnKullaniciSil" })</td>            
                <td>
                    @Ajax.ActionLink("Kullanici detayı göster", "KullaniciDetayi", "Kullanici", new { id = kullanici.Id },
               new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "kullaniciDetayi" }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="kullaniciDetayi"></div>

PersonelMVCUI1/Views/Kullanici/KullaniciDetayi.cshtml
@model IEnumerable<PersonelMVCUI1.Models.Entity_Framework.Kullanici>

<h1>Kullanıcının Detayı</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Personel Id</th>
            <th>Email Adresi</th>
            <th>Şifre</th>
            <th>Rolü</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kullanici in Model)
        {
            <tr>
                <td>@kullanici.PersonelId</td>
                <td>@kullanici.Email</td>
                <td>@kullanici.Sifre</td>
                <td>@kullanici.Role</td>
            </tr>
        }


    </tbody>
</table>

PersonelMVCUI1/Views/Kullanici/KullaniciForm.cshtml
@model PersonelMVCUI1.ViewModels.KullaniciFormViewModel

@{
    ViewBag.Title = "KullaniciForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mesaj">

</div>

<h2>Kullanıcı Formu</h2>
@using (Ajax.BeginForm("Kaydet", "Kullanici", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "mesaj" }))
{

    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.Kullanici.Email)
        @Html.TextBoxFor(m => m.Kullanici.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Kullanici.Email)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Kullanici.PersonelId)
        @Html.DropDownListFor(m => m.Kullanici.PersonelId, new SelectList(Model.Personeller, "Id", "Soyad"), "Personel Seçiniz", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Kullanici.PersonelId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Kullanici.Sifre)
        @Html.TextBoxFor(m => m.Kullanici.Sifre, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Kullanici.Sifre)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Kullanici.Role)
        @Html.TextBoxFor(m => m.Kullanici.Role, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Kullanici.Role)
    </div>


    @Html.HiddenFor(m => m.Kullanici.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>

}

@section scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}